# Generated by Django 3.2.1 on 2021-05-05 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='m_classroom',
            field=models.ManyToManyField(to='django_app.Classroom', verbose_name='Classrooms'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='e_date_debut',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 5, 16, 26, 40, 769050), verbose_name='date de debut'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='e_date_fin',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 5, 16, 26, 40, 769050), verbose_name='date de fin'),
        ),
    ]
