# Generated by Django 3.1.7 on 2021-05-05 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='e_date_debut',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 5, 14, 50, 50, 1196), verbose_name='date de debut'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='e_date_fin',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 5, 14, 50, 50, 1196), verbose_name='date de fin'),
        ),
    ]
