# Generated by Django 3.2.1 on 2021-05-06 09:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_app', '0002_auto_20210505_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='e_date_debut',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 11, 55, 39, 973687), verbose_name='date de debut'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='e_date_fin',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 11, 55, 39, 973687), verbose_name='date de fin'),
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pu_picture', models.ImageField(upload_to='profile')),
                ('pu_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='u_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
    ]
