# Generated by Django 3.2.1 on 2021-05-06 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_auto_20210506_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='e_date_debut',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 18, 24, 48, 925967), verbose_name='date de debut'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='e_date_fin',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 18, 24, 48, 925967), verbose_name='date de fin'),
        ),
        migrations.AlterField(
            model_name='supportdecours',
            name='sdc_matiere',
            field=models.ManyToManyField(related_name='m_support', to='django_app.Matiere', verbose_name='Support de cours'),
        ),
    ]
